### ISSUE TITLE
vertex groups functionality

### ISSUE THREAD

**Issue by Yerus** [BlenderNPR/Abnormal#1]
Hi!
I would very much like to know if abnormal will have connection with vertex groups in the future?
It would be really wonderful if it had. Any chance that the 'Point at target' function implements an object as a target for good and not only in edit time? Thx!

**Comment by CodyWinch** [comment]
It already has vertex group support. You can set the vertex group in the blender UI panel below the start modal button and change it through there while in the modal.

Point at target can be done with the Normal Edit modifier. Abnormal is only a temporary mode.
