### ISSUE TITLE
Installing error

### ISSUE THREAD

**Issue by Rogemcy** [BlenderNPR/Abnormal#10]
![20200607113451](https://user-images.githubusercontent.com/14737837/83959733-2c0ec800-a8b3-11ea-9a08-c6f40ab4aa20.png)

**Comment by CodyWinch** [comment]
This is in a custom build of blender? Does it occur in master?

**Comment by Rogemcy** [comment]
Yes.But it works in master very well now

Cody Winchester <notifications@github.com> 于2020年6月7日周日 下午12:12写道：
