### ISSUE TITLE
Cannot install the latest Master branch version 

### ISSUE THREAD

**Issue by Rogemcy** [BlenderNPR/Abnormal#12]
Failed to rotat viewport after clicking "Start Normal Editor " with latest master branch version in 2.90.1 official. BTW, the 1.1 version 
can not be installed .addon_utils.disable: Abnormal-1.1 not disabled
Modules Installed (Abnormal-1.1) from 'C:\\Users\\Administrator\\Desktop\\Abnormal-1.1.zip' into 'C:\\Users\\Administrator\\AppData\\Roaming\\Blender Foundation\\Blender\\2.90\\scripts\\addons'
Traceback (most recent call last):
  File "D:\YC CommonSoftware\Blender\2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Abnormal-1'

**Comment by CodyWinch** [comment]
For v1.1 you need to remove the -1.1 from the folders name for it to work.

For Master try it again. What keys do you use to rotate?
