### ISSUE TITLE
How to work with Subdivision?

### ISSUE THREAD

**Issue by lenetzp** [BlenderNPR/Abnormal#14]
Even edit with abnormal, it will not work after subdivision modifier.

**Comment by BlenderNPR** [comment]
you need to turn that on to see custom normal 
![image](https://user-images.githubusercontent.com/11452632/106161923-7fc37e00-61c2-11eb-9132-2e767d5c273f.png)

**Comment by lenetzp** [comment]
> you need to turn that on to see custom normal
> ![image](https://user-images.githubusercontent.com/11452632/106161923-7fc37e00-61c2-11eb-9132-2e767d5c273f.png)

Thank you, my version of blender is not support that.It is 2.83.
