### ISSUE TITLE
Cannot confirm changes

### ISSUE THREAD

**Issue by LinguiniThePasta** [BlenderNPR/Abnormal#15]
Python: Traceback (most recent call last):
  File "C:\Users\golde\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Abnormal-master\operators_modal.py", line 67, in modal
    status = basic_ui_hover_keymap(self, context, event)
  File "C:\Users\golde\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\Abnormal-master\functions_keymaps.py", line 66, in basic_ui_hover_keymap
    self.act_reg, self.act_rv3d, self._orbit_ob.location)
ReferenceError: StructRNA of type Object has been removed

location: <unknown location>:-1

**Comment by CodyWinch** [comment]
What steps did you take that led to this error?
Are there any error messages in the System Console before the one you provided?
Are you using the current master or an older version?

**Comment by CodyWinch** [comment]
I think I found the issue. It gives the error when clicking the confirm changes button.
The changes are being made though. For now you can use Tab to confirm and not get the error. I will get it fixed momentarilly

**Comment by CodyWinch** [comment]
Fix is now in master. Cancel and Confirm no longer give an error.
