### ISSUE TITLE
Exception: Shader Compile Error

### ISSUE THREAD

**Issue by kayse117** [BlenderNPR/Abnormal#16]
[Blender 2.92, MAC OS, MBP 2019 - AMD Radeon Pro 5500M 8 GB]

Wasn't sure if this add-on wasn't supported on Mac OS but I installed it and attempted to run the tool.
When attempting to run tool receive the following:

../operators_modal.py , line 242, in invoke

self._object.matrix_world.normalized())

../classes.py , line 12, in __init__

self.create_shader()

./classes.py , line 95, in create_shader

self.shader = gpy.types.GPUShader(vertex_shader, fragment_shader)

Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

Troubleshooting:
Uninstalled add-on and reinstalled per readme, still fails in the manner described above.

**Comment by CodyWinch** [comment]
Have you used previous versions successfully before?
If you haven't tried it, in the releases is Version 1.0 that uses older shaders that may work for your system.

**Comment by kayse117** [comment]
Let me give it a try and I will report back.

**Comment by kayse117** [comment]
> Have you used previous versions successfully before?
> If you haven't tried it, in the releases is Version 1.0 that uses older shaders that may work for your system.

That worked. Thank you! Do you know if future versions will be able to support OSX?

**Comment by CodyWinch** [comment]
I will try and make it so future versions can revert to older shaders as a backup option.

I am not a Mac user so I have no way to test the problem and get the newer shaders working for OSX.
