### ISSUE TITLE
Error with Abnormal

### ISSUE THREAD

**Issue by kimlori** [BlenderNPR/Abnormal#17]
<img width="2560" alt="error" src="https://user-images.githubusercontent.com/88216117/127721605-c24e3c8a-6ac0-496e-9e0f-c873da40f13b.png">

Hi! I get the error in the attached photo when I try to start Abnormal after installing the master zip. Do you happen to have any ideas on what I could try to get the error to disappear? Thank you!

**Comment by CodyWinch** [comment]
Can you share a screenshot of the error inside for the System Console?

**Comment by kimlori** [comment]
<img width="1088" alt="error 2" src="https://user-images.githubusercontent.com/88216117/127723597-31ea75b7-0ba8-4254-8999-03db6ee180ef.png">

Thank you!!

**Comment by CodyWinch** [comment]
I just pushed a commit that may fix it. It is hard for me to tell since I am not on a Mac.

**Comment by kimlori** [comment]
Thank you for your help!! :)

**Comment by circuitbone** [comment]
I can reproduce the error in 2.83 and 2.93

[Abnormals_Error_Test_Project_Blender2.93_MACOSX_10.13.6.blend.zip](https://github.com/bnpr/Abnormal/files/6911990/Abnormals_Error_Test_Project_Blender2.93_MACOSX_10.13.6.blend.zip)


Some shader compile error on mac?


```
> Traceback (most recent call last):
>   File "/Users/xxxx/Library/Application Support/Blender/2.83/scripts/addons/Abnormal-master/operators_modal.py", line 242, in invoke
>     self._object.matrix_world.normalized())
>   File "/Users/xxxx/Library/Application Support/Blender/2.83/scripts/addons/Abnormal-master/classes.py", line 12, in __init__
>     self.create_shader()
>   File "/Users/xxxx/Library/Application Support/Blender/2.83/scripts/addons/Abnormal-master/classes.py", line 96, in create_shader
>     self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
> Exception: Shader Compile Error, see console for more details
> 
> location: <unknown location>:-1
> 
> 
```

**Comment by CodyWinch** [comment]
> 
> 
> I can reproduce the error in 2.83 and 2.93
> 
> [Abnormals_Error_Test_Project_Blender2.93_MACOSX_10.13.6.blend.zip](https://github.com/bnpr/Abnormal/files/6911990/Abnormals_Error_Test_Project_Blender2.93_MACOSX_10.13.6.blend.zip)
> 
> Some shader compile error on mac?
> 
> ```
> > Traceback (most recent call last):
> >   File "/Users/xxxx/Library/Application Support/Blender/2.83/scripts/addons/Abnormal-master/operators_modal.py", line 242, in invoke
> >     self._object.matrix_world.normalized())
> >   File "/Users/xxxx/Library/Application Support/Blender/2.83/scripts/addons/Abnormal-master/classes.py", line 12, in __init__
> >     self.create_shader()
> >   File "/Users/xxxx/Library/Application Support/Blender/2.83/scripts/addons/Abnormal-master/classes.py", line 96, in create_shader
> >     self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
> > Exception: Shader Compile Error, see console for more details
> > 
> > location: <unknown location>:-1
> > 
> > 
> ```

Can you share the screenshot of the full system console error? There should be more info above that.
Yes I believe this is a Mac specific issue. I will work on a version with a optional different draw system for macs.

**Comment by circuitbone** [comment]
Apologies I am very new to Blender ( few months in )

`bpy.context.area.ui_type = 'VIEW_3D'
bpy.ops.abnormal.normal_editor_modal()
`
Is what appears above the error message.

**Comment by CodyWinch** [comment]
![Capture](https://user-images.githubusercontent.com/10019228/127756819-6b0a678a-1dd7-4148-a13d-2e7cc20ab02a.PNG)
This is where you get the system console. It will open a window with a bunch of text. Share a screenshot of that starting with the first error. It will be a big block of text like in the shared screenshot above.

**Comment by circuitbone** [comment]
The mac has nothing there, I had to launch a terminal at the same time as the Blender application according to this article.

https://blender.stackexchange.com/questions/102860/how-to-open-system-console-to-get-output-from-blender-on-mac-os-10
![Screen Shot 2021-08-01 at 12 26 04 pm](https://user-images.githubusercontent.com/47682220/127757109-b1a2c6d7-ad9e-40c3-8d0b-656b72467264.png)



A naming convention of the shader appears to be one of the errors.

```

Last` login: Sun Aug  1 08:52:56 on ttys000
-bash: KDE: command not found
/Applications/Blender\ 2.93.app/Contents/MacOS/Blender ; exit;
ds-mbp-2k15B:~ davidsmith$ /Applications/Blender\ 2.93.app/Contents/MacOS/Blender ; exit;
Read prefs: /Users/davidsmith/Library/Application Support/Blender/2.93/config/userpref.blend
register_class(...):
Warning: 'object.custom_menu' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'object.custom_panel' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'object.bygenmodify' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'object.bygentools' does not contain '_PT_' with prefix and suffix
register_class(...):
Warning: 'mwse_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'mws_tool_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'mwse_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'mws_tool_pie' does not contain '_MT_' with prefix and suffix
register_class(...):
Warning: 'SoftMod_PT_Panel' doesn't have upper case alpha-numeric prefix
Imported mesh_maze.py
register_class(...):
Warning: 'object_PT_Panel' doesn't have upper case alpha-numeric prefix
Read blend: /Users/davidsmith/Desktop/Abnormals_Error_Test_Project_Blender2.93_MACOSX_10.13.6.blend
ERROR (gpu.shader): pyGPUShader FragShader: 
      | 
      | Error: Identifier name 'gl_FragColor' cannot start with 'gl_'
      | 
      | Error: Use of undeclared identifier 'gl_FragColor'

Python: Traceback (most recent call last):
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 12, in __init__
    self.create_shader()
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 96, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 12, in __init__
    self.create_shader()
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 96, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1
```

**Comment by CodyWinch** [comment]
Alright, it seems gl_FragColor is no longer supported in newer OpenGL versions which I guess Mac is using the newer version.
Try the new one and let me know if that works.

**Comment by circuitbone** [comment]
Ok that results in this data


```
ERROR (gpu.shader): pyGPUShader FragShader: 
      | 
      | Error: Use of undeclared identifier 'gl_FragColor'

Python: Traceback (most recent call last):
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 12, in __init__
    self.create_shader()
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 95, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/operators_modal.py", line 241, in invoke
    self._container = ABNContainer(
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 12, in __init__
    self.create_shader()
  File "/Users/davidsmith/Library/Application Support/Blender/2.93/scripts/addons/Abnormal-master/classes.py", line 95, in create_shader
    self.shader = gpu.types.GPUShader(vertex_shader, fragment_shader)
Exception: Shader Compile Error, see console for more details

location: <unknown location>:-1

```
![Screen Shot 2021-08-01 at 12 54 33 pm](https://user-images.githubusercontent.com/47682220/127757589-8b67192e-219c-4ae4-ba0b-fb5c93d1fe30.png)

**Comment by circuitbone** [comment]
Assuming it has something to do with that outdated fragcolor name

https://stackoverflow.com/questions/26695253/when-switching-to-glsl-300-met-the-following-error

**Comment by CodyWinch** [comment]
Yeah that is what I thought I just changed.

There should no longer be any gl_FragColor being used.

**Comment by CodyWinch** [comment]
I tried to setup a Mac virtual machine, but it won't open blender.

I just commited another setup that I use in another addon so give it another try with a clean install of abnormal.

**Comment by circuitbone** [comment]
Are you suggesting addons can clash? 

- [x] Testing Blender 2.93 with solo addon abnormal only installed - FAIL
![Screen Shot 2021-08-03 at 8 12 50 am](https://user-images.githubusercontent.com/47682220/127930366-927bf68d-28ac-446e-9fa9-ee6e9f1bbb2d.png)

**Comment by circuitbone** [comment]
Did you try sosumi in a snap or a disc image?

https://snapcraft.io/install/sosumi/ubuntu

http://dosdude1.com/

**Comment by CodyWinch** [comment]
> 
> 
> Are you suggesting addons can clash?
> 
>     * [x]  Testing Blender 2.93 with solo addon abnormal only installed - FAIL
>       ![Screen Shot 2021-08-03 at 8 12 50 am](https://user-images.githubusercontent.com/47682220/127930366-927bf68d-28ac-446e-9fa9-ee6e9f1bbb2d.png)

No, I mean that sometimes people can mess up the install of a new version of the addon, but still have the old version messing things up. So doing a clean install of Abnormal by manually deleting its folder can help.

I will look into sosumi.

**Comment by circuitbone** [comment]
no sweat.

**Comment by CodyWinch** [comment]
I just commited an alternate draw system for Mac users that will only use the built in shaders with blenders gpu module.

You can turn it on in the addon preferences here.
![Capture](https://user-images.githubusercontent.com/10019228/127950055-d643cce6-c5c4-444c-b188-af24b085e1aa.PNG)

**Comment by circuitbone** [comment]
After trashing the directory manually and then restarting I could see the menu...

Thanks so much it works now mate! 👍
![Screen Shot 2021-08-03 at 1 01 21 pm](https://user-images.githubusercontent.com/47682220/127951046-f451fff5-6752-4415-91e3-3e2149094101.png)
