### ISSUE TITLE
ABN_OT_normal_editor_modal.invoke( ) fails due to not being able to find the "check_area" function

### ISSUE THREAD

**Issue by Kolupsy** [BlenderNPR/Abnormal#18]
I just installed the latest version of abnormal (1.1) to Blender 2.93 LTS and tried to use the normal editor but it fails to invoke the modal because the operator fails to access the "check_area" function. 

```
Abnormal-master\operators_modal.py", line 85, in invoke
    self.act_reg, self.act_rv3d = check_area(self)
NameError: name 'check_area' is not defined
```

There seems to be a problem with importing from modules using the asterisk. Editing the code to specifically importing the function in operators_modal.py like this:

`from .functions_modal import check_area`

fixes the issue for me

**Comment by CodyWinch** [comment]
What system are you on? I don't run into this on Windows with the LTS version.

**Comment by Kolupsy** [comment]
its windows 10. Its really strange because there shouldnt be a problem using the asterisk (aside from making it a bit harder to find where code snippets come from :) )

**Comment by Kolupsy** [comment]
also unrelated but the default selection scheme for abnormal is right click select. Now i use left click select for everything else. Am i gonna run into issues if i change the addon preferences or even better, could it be possible for the addon to detect what the system selection scheme is?

**Comment by CodyWinch** [comment]
No that won't cause issues. The addon preferences are used for the keystrokes.
