### ISSUE TITLE
Conflict with color management（ACES OpenColorIO）

### ISSUE THREAD

**Issue by KamiaoChan** [BlenderNPR/Abnormal#19]
conflict with blender with aces color management file
the previous version did not have this problem
ace file download：https://drive.google.com/drive/folders/12uJSOyFfjaqO7t5F5HVBmGnrT2G1rlJK?usp=sharing
[error.txt](https://github.com/bnpr/Abnormal/files/6924335/error.txt)
![error](https://user-images.githubusercontent.com/42341297/128022386-22dd2ce1-0908-45bf-a272-10733f41b458.png)

**Comment by CodyWinch** [comment]
Just commited a fix for this. Now will only set to Raw if it is available.
