### ISSUE TITLE
Bug with Incremental Rotations

### ISSUE THREAD

**Issue by uayten** [BlenderNPR/Abnormal#20]
whenever I add vertices to my mesh, I need to edit the normals, that's the default and that's fine, but when I want to rotate the normals on the Z axis by 15 by 15 degrees, I can't because the "Incremental Rotations" doesn't seem to be working properly when the normals are aligned.
I made a video to show the problem:
https://youtu.be/DhngytHPEk0

I would also like to suggest the addition of an option to pre-configure an angulation referring to a specific vertex group.

Example:
1 I want a part of the face to always be aligned in the "Axis -Y"
2 I create a "vertex group" for these vertices
3 I leave it configured in the addon that that vertex group will always be "Axis -Y"
4 if I add vertices in this "vertex group", the addon can update them
5 do this with multiple "vertex groups" and different angles.

https://i.imgur.com/v6MTunc.jpg
as you can see, my character's face is separated according to the angles I want to put in the abnormal,
so it's a lot of work to always have to select the part I want and configure and leave it at the right angle

since now, thanks for your attention 

video explaining the technique used
https://youtu.be/5eSTrYANNZ0

**Comment by CodyWinch** [comment]
Commited a fix for the incremental rotation issue.
