### ISSUE TITLE
Cannot Start Normal Editor

### ISSUE THREAD

**Issue by zihang-huang** [BlenderNPR/Abnormal#24]
I tried to use this add-on on my M1Max MacBook Pro, but the normal editor cannot be opened.

My Blender version is 3.1.2(Apple Silicon), and the add-on version is 1.1.2
![image](https://user-images.githubusercontent.com/56563171/168771572-d4b87023-803b-4d58-b819-633e4f5d35d7.png)

**Comment by CodyWinch** [comment]
![image](https://user-images.githubusercontent.com/10019228/168772192-c23f21e5-39c2-43c0-82ca-19c4d85da0fd.png)
Enable this option in the addon preferences for Mac

**Comment by zihang-huang** [comment]
> ![image](https://user-images.githubusercontent.com/10019228/168772192-c23f21e5-39c2-43c0-82ca-19c4d85da0fd.png)
> Enable this option in the addon preferences for Mac

Thank you!!!! Problem solved!!!
