### ISSUE TITLE
Abnormal crashes when attempting to edit normals from camera view

### ISSUE THREAD

**Issue by TheFriendlyRabbit** [BlenderNPR/Abnormal#26]
Issue at https://github.com/bnpr/Abnormal/blob/master/functions_general.py#L681

``flat_locs`` is never set if the camera's perspective is neither perspective nor orthographic. This causes a crash when it is referenced.

**Comment by CodyWinch** [comment]
Thanks for the report! Fixed now in Master and 1.2
