### ISSUE TITLE
Not working on blender 3.3 LTS?

### ISSUE THREAD

**Issue by Livb-VRC** [BlenderNPR/Abnormal#27]
I just tried installing this but I don't see it on the tools panel

**Comment by cenlyy** [comment]
Me Toooo！！！Also can't find it in tools in 3.3

**Comment by cenlyy** [comment]
change to 2.8 and still didnt work

**Comment by bmourit** [comment]
This is an issue with the way the release folder was named before it was compressed.
To fix it:
-Download and unzip the addon
-Change the name of the folder so that it has no '.' (dot, period). You may replace them with underscores
    Example: Abnormal-1.1.2 -> Abnormal-1_1_2
-Rezip the folder and install as normal

Good luck!

**Comment by MapleSenpai** [comment]
> This is an issue with the way the release folder was named before it was compressed. To fix it: -Download and unzip the addon -Change the name of the folder so that it has no '.' (dot, period). You may replace them with underscores Example: Abnormal-1.1.2 -> Abnormal-1_1_2 -Rezip the folder and install as normal
> 
> Good luck!

funny thing is the latest zip files reads "**abnormal-master.zip**". There isnt any period anywhere to rename. While the addon loads up in blender in the N panel, starting the normal editor loads up a bunch of errors and nothing happens

**Comment by bmourit** [comment]
Assuming you are using the latest changes from unreleased version, well - this is the risk you take with using an unreleased (development) version. The latest official release works with renaming.

If you are referring to the 1.1.2 release. You have to unzip it first to see the folder inside is named Abnormal-1.1.2. That is what you have to rename before rezipping the folder. The name of the zip file is fine. It is the folder inside that needs changed.

**Comment by bsl888** [comment]
I download 1.1.2 and setup it in blender3.3.
it works...BUT Blendr call me this:
![image](https://user-images.githubusercontent.com/120531879/207475633-70dfcae1-4153-41fb-b91d-6769fc896027.png)

I remove plugins in Blender,then I go and check Administrator\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons   

 I'm really sure it hasbeen removed already,but when i restart my computer and Blender,
The keyerror never stop..

PS:the filedata named Abnormal in zip, setup the zip in Blender 3.3 or unpack it in  Administrator\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons   are same...

please fix it..... i can't work in blender now.....

**Comment by CodyWinch** [comment]
> I just tried installing this but I don't see it on the tools panel

I just tested with the Master version and Abnormal-master.zip of the Release version 1.1.2 It works for me, but I did have the same issue where after installing it was not in the N panel.

After you install it make sure to save your preferences and then restart blender. It should then show up in the N panel like it did for me.

I will look into why this is an issue when I have time, but for now it still works once you get it installed.

If you use the release version I would avoid using the zip that is named Abnormal-1.1.2 or similar numbers.
Github adds those numbers to the zip and I can't seem to prevent it. The Abnormal-master.zip is added by me to avoid the issue that bmourit mentioned.

**Comment by CodyWinch** [comment]
> I download 1.1.2 and setup it in blender3.3. it works...BUT when i click in viewer anytime Blender will call me this: ![image](https://user-images.githubusercontent.com/120531879/207475633-70dfcae1-4153-41fb-b91d-6769fc896027.png)
> 
> I remove plugins in Blender,then I go and check Administrator\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons ,make sure "Abnormal" removed.
> 
> ![image](https://user-images.githubusercontent.com/120531879/207476893-409469ae-68a6-4ea6-9f0c-e932ff39f699.png) ![image](https://user-images.githubusercontent.com/120531879/207477080-057a3f25-ab50-452c-8f2f-f94bf5959f0a.png)
> 
> I'm really sure it hasbeen removed now,but when i restart my computer and Blender, The keyerror never stop..
> 
> PS:the filedata named Abnormal in zip, setup the zip in Blender 3.3 or unpack it in Administrator\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons are same...
> 
> I change the Blender 3.1 ,same problem.
> 
> please tell me how can I cleanly it?

This seems like a different issue than the one started here. If you could report this as a separate issue I can look into it.
