### ISSUE TITLE
Error for executing Abnormal 

### ISSUE THREAD

**Issue by tri333ple** [BlenderNPR/Abnormal#30]
Any ideas? 

![image](https://github.com/bnpr/Abnormal/assets/69550033/6abb4072-7a66-4865-8bf5-8bfb15c3653b)

**Comment by CodyWinch** [comment]
I just tested the most recent release in 3.4 3.5 and 3.6 and they all still work correctly for me.
If you could share a screenshot or paste what your system console shows after this error that would be helpful.

You could also use the Use Alternative Drawing option in the addon preferences.
![image](https://github.com/bnpr/Abnormal/assets/10019228/6fb8e6d9-7eb5-4fcb-8f65-fd9d2d54319c)

**Comment by tri333ple** [comment]
hey cody thanks for getting back just going to shut this ticket. Ended up working after i did some reinstalls
