### ISSUE TITLE
Shader Exception when pressed Start Normal Editor - latest versions of blender and addon, Use Alternative Drawing doesn't fix.

### ISSUE THREAD

**Issue by DigitalTether** [BlenderNPR/Abnormal#34]
Hi, I'm getting this error message when I press Start Normal Editor
![image](https://github.com/bnpr/Abnormal/assets/32414816/18a3bcd5-a0f1-4e5b-9163-36fc30f1467e)

I'm on Windows 10, using Blender 4.0.1, with addon release version 1.2.
Done the full reinstall procedure, and enabled Use Alternative Drawing option in addon (because I saw that suggestion in other tickets).
I've also installed blender onto a second drive from my main (default) one if that's at all relevant.

Thank you.

**Comment by CodyWinch** [comment]
If you download the master version this should be fixed.
![image](https://github.com/bnpr/Abnormal/assets/10019228/7ce07218-d14f-4353-a913-b89c51bcb426)

**Comment by DigitalTether** [comment]
Yep, that did it. Thanks for the quick response.
