### ISSUE TITLE
Blender 4.1 ; No more "use_auto_smooth"

### ISSUE THREAD

**Issue by NiyahVE** [BlenderNPR/Abnormal#37]
Since in the latest blender version auto_smooth got replaced by a modifier, Abnormal is not working as intended and just throw this error when clicking "Start normal editor"

![image](https://github.com/bnpr/Abnormal/assets/13157783/25be2268-4ba0-4a2f-a6d3-dfc07381b54b)

I'm not tech savy enough to fix this sadly, if anyone could help that'd be great !

**Comment by CodyWinch** [comment]
This is fixed in the newest release
