### ISSUE TITLE
Not really an issue, more like a guide

### ISSUE THREAD

**Issue by okuma10** [BlenderNPR/Abnormal#4]
Hi there, sorry for writing in the issues, but can you point me to the file where you've solved the multiple view port drawing?
I've been struggling to on this for months, to the point that I just left it for sometime in the future.
But watching the BNPR show and hearing you've solved it, got me excited to implement it again, but since you already found the way, I thought that I should try and ask for guide, if you don't mind.

**Comment by BlenderNPR** [comment]
It is in master right now. Please remove your old Adnormal add-on and reinstall the new version. Also restart Blender after that.

**Comment by CodyWinch** [comment]
This is accomplished by storing the context.area in the modal invoke as
self._area. then in the drawing it checks if the draw_callback_2d
context.area == self._area before doing the drawing. Preventing other areas
from drawing

**Comment by okuma10** [comment]
Hmm...the thing is that if I check the context.area.type I'll get "VIEW_3D". That's the part I'm having a hard time to wrap my head around. How to say..."ok draw in this 'VIEW_3D' not this 'VIEW_3D' "

At one point I was thinking of using the as_pointer() to identify the views, as that will give an ID that is unique to every instance of VIEW_3D . But I couldn't imagine how I will say "VIEW_3D draw only if you have this specific as_pointer() number". Since from what I understand once we add the draw handler...it applies to all areas of the type VIEW_3D. And it takes a simple tag to update the view 3D to have it appear in that view. Like rotating the view triggers the update function.

Eventually you can point me to the file and I can try to figure it out from there.

**Comment by CodyWinch** [comment]
It is in
operators_modal.py line 168
functions_drawing.py line 157

You could use as_pointer most likely, but I found just doing a check that
the stored area == the current draw area is sufficient.

**Comment by okuma10** [comment]
Thanks! I'll try to figure it out from there.
But yeah...I guess if you store the VIEW_3D in a variable, it will come with it's own unique memory location, so as_pointer() is a bit useless, unless I store only the pointer number and not the whole VIEW_3D

Ah! I see now....man I'm dumb. I made the error in thinking that there is some trick to tell blender not have that code in it's draw handler for that view. While you just told it "unless you are this view, do not do drawing".
I guess I have to place my "listener" function that handles user input inside that if statement as well to make sure the other views aren't checking for clicks and mouse position as well.
