### ISSUE TITLE
UI doesn't scale at 4k resolution

### ISSUE THREAD

**Issue by laruda** [BlenderNPR/Abnormal#5]
The addon works well at 1080p but not at higher resolution
https://i.imgur.com/O0FYOsZ.jpg

**Comment by CodyWinch** [comment]
Thanks I will implement a ui scale value.

**Comment by CodyWinch** [comment]
I have uploaded an initial fix for this. Please test it and let know if it works better.

**Comment by laruda** [comment]
it works pretty well, thank you <3
