### ISSUE TITLE
How to I download this add-on

### ISSUE THREAD

**Issue by Questions1213** [BlenderNPR/Abnormal#6]
I not sure how to download this add-on  I don't really use add-ons but this is great for NPR could someone please explain.

**Comment by BlenderNPR** [comment]
Please read: https://github.com/BlenderNPR/Abnormal#first-installation

**Comment by Questions1213** [comment]
That didn't work

**Comment by BlenderNPR** [comment]
Download: https://github.com/BlenderNPR/Abnormal/archive/master.zip
