### ISSUE TITLE
Is there a way to scale the ui

### ISSUE THREAD

**Issue by Questions1213** [BlenderNPR/Abnormal#7]
Is there a way to scale the ui because it appears very small.

**Comment by CodyWinch** [comment]
The latest version scales to the size of your screen now, but there is currently no way to change it further.

**Comment by Questions1213** [comment]
Ok thanks

**Comment by CodyWinch** [comment]
There is a new version of Abnormal V1.1 that has an update UI with the option to change the UI scale. You can get it from V1.1 branch.
