### ISSUE TITLE
Error on using spherize, point to target

### ISSUE THREAD

**Issue by oik976** [BlenderNPR/Abnormal#8]
Hi there-

Looks like a minor change was missed in your last update. In **functions_modal.py** on line 558 (start_spherize_mode) and line 662 (start_point_mode) the scale parameter is missing. I updated it to the following:
`subp = panel.add_subpanel(self._window.scale, header_text='')` based off of your implementation in **operators_modal.py**.

Thanks for the great tool, and hope you don't mind me kabitzing if anyone else runs into this issue.

**Comment by CodyWinch** [comment]
Thank you for pointing that out. I just uploaded the fix
