### ISSUE TITLE
3D viewport rotating  faild

### ISSUE THREAD

**Issue by Rogemcy** [BlenderNPR/Abnormal#9]
Hi,thanks for your developing of this awsome addon! I've test the latest version in the 2.83,and I found that I can't rotate 3D viewport when I  activated the Abnormal addon.
PS:Do you have Wechat or Alipay account? Leave a QR code on the website and you may recive donations directly(I'm Chinese ,the paypal is fuzzy and somehow it did't work,I knew some guys in China are interested in Blender stylized rendering,I hope it can help).

**Comment by CodyWinch** [comment]
What keys do you normally use to rotate the viewport?

The addon by default uses whatever your keymap is to rotate.

**Comment by Rogemcy** [comment]
MMB by default

Cody Winchester <notifications@github.com> 于2020年6月7日周日 上午10:36写道：

**Comment by Rogemcy** [comment]
MMB by default. And I can rotate the viewport corretly when the addon is  unactivated.

**Comment by CodyWinch** [comment]
I uploaded a minor tweak to how it loads the navigation list. 

Try that out. If that does not work can you tell me what does happen and if any sort of errors are shown in the system console?

**Comment by Rogemcy** [comment]
Fixed . Thanks ! The errors occurs in  another branch of blender called
“outline_node_branch (v2.83)，I use it for realtime edgedetecting while
LANPR pause updating temporary  ” ,but  in the official branch  works well.
[image: 20200607113451.png]

Cody Winchester <notifications@github.com> 于2020年6月7日周日 上午11:28写道：

**Comment by CodyWinch** [comment]
Great. LANPR is under development and I believe changing from a separate render engine to just a grease pencil generator of some sorts. Once it is in master we will make sure it doesn't interfere with abnormal.

**Comment by Rogemcy** [comment]
I met the problem again ,but this time it happened in 2.83 official.Here is
the file.

Cody Winchester <notifications@github.com> 于2020年6月7日周日 上午11:57写道：

**Comment by CodyWinch** [comment]
There is no file attached.

What are your Input and Navigation settings in Blenders Preferences?
